#!/bin/bash
########################################################################################
pacman -S --needed base-devel git
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si
########################################################################################
########################################################################################
sudo pacman -S coreutils curl grep sed wget sudo binutils less unzip tar
mkdir -p /tmp/am && pushd /tmp/am
pushd /tmp/am
wget https://raw.githubusercontent.com/ivan-hc/AM/main/INSTALL && chmod a+x ./INSTALL && sudo ./INSTALL
popd
rm -rf /tmp/am
########################################################################################
# install aur packages
paru -S --noconfirm --needed 
am -i obsidian cursor